---

.script-vagrant: &script-vagrant
  - |
    curl -Os https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
    sudo dpkg -i vagrant_2.2.14_x86_64.deb
    rm -rf vagrant_2.2.14_*

.script-libvirt: &script-libvirt
  - |
    sudo apt-get update
    sudo apt-get install -y binutils bridge-utils dnsmasq-base ebtables gcc libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev make qemu-kvm qemu-utils ruby-dev
    vagrant plugin install vagrant-libvirt

.script-ansible: &script-ansible
  - |
    sudo apt-get update
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --ignore-installed --requirement requirements.txt

.script-molecule: &script-molecule
  - |
    source ./scripts/run-tests.sh
    sudo -E molecule test -s $MOLECULE_SCENARIO_NAME

.job-molecule: &job-molecule
  script:
    - *script-vagrant
    - *script-libvirt
    - *script-ansible
    - *script-molecule

default:
  before_script:
    - |
      git submodule sync --recursive
      git submodule update --init --recursive
    
    - |
      export ROLE=$(echo $CI_PROJECT_NAME | sed 's/^ansible-role-//g')
      mkdir -p $HOME/.ansible/roles
      ln -s $CI_PROJECT_DIR $HOME/.ansible/roles/$ROLE

ubuntu-20.04:
  <<: *job-molecule
  stage: build
  variables:
    MOLECULE_SCENARIO_NAME: "ubuntu-20.04"

ubuntu-18.04:
  <<: *job-molecule
  stage: build
  variables:
    MOLECULE_SCENARIO_NAME: "ubuntu-18.04"

ubuntu-20.10:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "ubuntu-20.10"

centos-8:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "centos-8"

centos-7:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "centos-7"

suse-15:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "suse-15"

debian-10:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "debian-10"

fedora-33:
  <<: *job-molecule
  stage: test
  allow_failure: true
  variables:
    MOLECULE_SCENARIO_NAME: "fedora-33"

ansible-galaxy:
  stage: deploy
  script:
    - *script-ansible
    - |
      sudo ansible-galaxy role import --token $ANSIBLE_GALAXY_API_KEY $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME
