---

# Copyright 2023 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: rpm --import
  vars:
    ansible_python_interpreter: "python3"
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    fingerprint: "{{ item.fingerprint }}"
    state: "{{ item.state }}"
  loop: "{{ _rpm_key }}"
  register: result
  until: result is succeeded

- name: yum-config-manager --add-repo
  ansible.builtin.yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    priority: "{{ item.priority }}"
    module_hotfixes: "{{ item.module_hotfixes }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state }}"
    reposdir: "{{ item.reposdir | default('/etc/zypp/repos.d') }}"
  loop: "{{ _yum_repository }}"

- name: zypper removelock
  ansible.builtin.command:
    cmd: zypper removelock {{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\..*$', '\1-*') }}
  loop: "{{ _zypper }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false

- name: zypper install
  vars:
    ansible_python_interpreter: "python3"
  community.general.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    force_resolution: true
  loop: "{{ _zypper }}"
  register: result
  until: result is succeeded
  notify:
    - jira | systemctl restart jira.service

- name: zypper addlock
  ansible.builtin.command:
    cmd: zypper addlock {{ item.name | regex_replace('^(.*)-[0-9]*:*[0-9]+\..*$', '\1-*') }}
  loop: "{{ _zypper }}"
  when: item.state == "present"
  changed_when: false
  failed_when: false
