---

- hosts: all
  remote_user: root
  become: true
  gather_facts: false
  tasks:
    - name: install ca-certificates curl python3 sudo
      raw: |
        if [ -x "$(command -v apt-get)" ]
        then
          apt-get update && apt-get install -y ca-certificates curl python3 sudo
        elif [ -x "$(command -v yum)" ]
        then
          yum install -y ca-certificates curl python3 sudo
        elif [ -x "$(command -v zypper)" ]
        then
          zypper -n --gpg-auto-import-keys refresh && zypper -n install -y ca-certificates* curl python3 python3-xml sudo
        fi
      register: result
      changed_when: result is not succeeded
