---

- hosts: all
  remote_user: root
  become: true
  gather_facts: false
  tasks:
    - name: cat > /etc/environment <<EOF
      raw: |
        cat > /etc/environment <<EOF
        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        EOF

    - name: ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf
      raw: |
        if [ -f "/run/systemd/resolve/resolv.conf" ]
        then
          ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf
        fi

    - name: cat > /etc/resolv.conf <<EOF
      raw: |
        cat > /etc/resolv.conf <<EOF
        search localdomain
        nameserver 8.8.8.8
        nameserver 8.8.4.4
        EOF

    - name: redhat-7 | subscription-manager register
      raw: |
        if [ -x "$(command -v subscription-manager)" ]
        then
          subscription-manager register \
            --username={{ lookup('env', 'REDHAT_USERNAME') }} \
            --password={{ lookup('env', 'REDHAT_PASSWORD') }} \
            --autosubscribe
        fi

    - name: redhat | systemctl stop firewalld
      raw: |
        if [ -x "$(command -v firewalld)" ]
        then
          systemctl stop firewalld
        fi

    - name: debian | systemctl stop ufw
      raw: |
        if [ -x "$(command -v ufw)" ]
        then
          systemctl stop ufw
        fi

    - name: redhat | yum install ca-certificates curl python3 sudo
      raw: |
        if [ -x "$(command -v yum)" ]
        then
          yum install -y ca-certificates curl python3 sudo
        fi

    - name: suse | zypper install ca-certificates* curl python3 python3-xml sudo
      raw: |
        if [ -x "$(command -v zypper)" ]
        then
          zypper -n --gpg-auto-import-keys refresh
          zypper -n install -y ca-certificates* curl python3 python3-xml sudo
        fi

    - name: debian | apt-get install ca-certificates curl python3 sudo
      raw: |
        if [ -x "$(command -v apt-get)" ]
        then
          apt-get update
          apt-get install -y ca-certificates curl python3 sudo
        fi
